### ISSUE TITLE
there is no end game

### ISSUE THREAD

**Issue by bburnett2** [bburnett2/TextBasedGame#19]
when you defeat the final monster, nothing happens.  There is also nothing in the documentation on what is suppose to happen, on a side not I think we forgot to put that in our RE document as well.

**Comment by Michaelh87** [comment]
Wow you got to the final monster.  yay.  We just need to do a splash screen of our names and the game title.

Michael

Sent from my Sprint Samsung Galaxy S7.

-------- Original message --------

**Comment by bburnett2** [comment]
I cheated, I went into the database and set the current room = 46 so i could test the final puzzle

**Comment by Michaelh87** [comment]
end game splash screen is added.  Feel free to ad anything else you would like
