### ISSUE TITLE
"use c" giving +5 max health infinitely

### ISSUE THREAD

**Issue by marcusmoss** [bburnett2/TextBasedGame#24]
Might be related to the other issue, but after picking up the Health Capsule, you can "use c" at any time to increase your maximum health by 5.

**Comment by Michaelh87** [comment]
Can you explain this more.  maybe print screen the out put.

Michael

Sent from my Sprint Samsung Galaxy S7.

-------- Original message --------

**Comment by marcusmoss** [comment]
Github refuses to accept the file. Basically, you pick up the "Health Capsule" item on level 6. After that, typing "use anything"  increases your maximum health by 5. I thought it was just "use c", but "use bacon" and "use aljwedjklhqjkh3" also work.

**Comment by Michaelh87** [comment]
I don't know I have to look at that shortly

Sent from my Sprint Samsung Galaxy S7.

-------- Original message --------
