### ISSUE TITLE
use item and equip item

### ISSUE THREAD

**Issue by Michaelh87** [bburnett2/TextBasedGame#3]
They need to implemented from he condoler on thru the model and printed to the view.

**Comment by Michaelh87** [comment]
equip has been defined but need to be tested

for testing to pass it needs to move item from unequippedItems to equppedItems and add the attributes to player.

**Comment by bburnett2** [comment]
equip throws an error because it is trying to remove an item from the arrayList while traversing the arrayList

**Comment by Michaelh87** [comment]
working
