### ISSUE TITLE
Room restricutions

### ISSUE THREAD

**Issue by Michaelh87** [bburnett2/TextBasedGame#8]
Room 12 cannot go east till completing a puzzle 8 and room 25 are restricted on going east till puzzle 4 is completed.  

the DB store a restriction String (puzzle, direction(the room ID))  pass two numbers
pars (,)

In the room it will be stored into two variables.  
Ever time you go a direction you have to check if that room is restricted and then if the puzzle is completed.

**Comment by bburnett2** [comment]
database side resolved
